import 'package:get/get.dart';
import 'package:hive/hive.dart';
part 'cart_item_model.g.dart'; // Generated by Hive

@HiveType(typeId: 1)
class CartItemModel extends HiveObject {
  @HiveField(0)
  String arOfferTitle;

  @HiveField(1)
  String enOfferTitle;

  @HiveField(2)
  int offerId;

  @HiveField(3)
  int offerOptionsId;

  @HiveField(4)
  int cartId;

  @HiveField(5)
  double pricePerItem;

  @HiveField(6)
  RxInt count = 0.obs;

  @HiveField(7)
  double totalPrice;

  @HiveField(8)
  int? id;

  @HiveField(9)
  String offerKey;

  @HiveField(10)
  String mainImage;

  @HiveField(11)
  String companyLogo;

  @HiveField(12)
  String companyName;

  @HiveField(13)
  String enCompanyName;

  CartItemModel({
    required this.arOfferTitle,
    required this.enOfferTitle,
    required this.offerId,
    required this.offerKey,
    required this.offerOptionsId,
    required this.cartId,
    required this.pricePerItem,
    required this.count,
    required this.totalPrice,
    required this.mainImage,
    required this.companyLogo,
    required this.companyName,
    required this.enCompanyName,
    this.id,
  });

  factory CartItemModel.fromJson(Map<String, dynamic> json) {
    return CartItemModel(
      id: json['id'] as int,
      offerKey: json['offerKey'] as String,
      arOfferTitle: json['arOfferTitle'] as String,
      enOfferTitle: json['enOfferTitle'] as String,
      offerId: json['offerId'] as int,
      offerOptionsId: json['offerOptionsId'] as int,
      cartId: json['cartId'] as int,
      pricePerItem: json['pricePerItem'].toDouble(),
      count: (json['count'] as int).obs,
      totalPrice: json['totalPrice'].toDouble(),
      mainImage: json['mainImage'] as String,
      companyLogo: json['companyLogo'] as String,
      companyName: json['companyName'] as String,
      enCompanyName: json['enCompanyName'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      "arOfferTitle": arOfferTitle,
      "enOfferTitle": enOfferTitle,
      "offerId": offerId,
      "offerKey": offerKey,
      "offerOptionsId": offerOptionsId,
      "cartId": cartId,
      "pricePerItem": pricePerItem,
      "count": count.value,
      "totalPrice": totalPrice,
      'companyName': companyName,
      'enCompanyName': enCompanyName,
    };
  }

  int getQuantity() {
    return count.value;
  }

  void incrementQuantity() {
    count++;
    // save(); // Save the updated CartItemModel in Hive
  }

  void decrementQuantity() {
    if (count > 1) {
      count--;
      // save(); // Save the updated CartItemModel in Hive
    }
  }
}
