name: test_ecommerce_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  get:
  get_storage:
  iconly:
  freezed_annotation:
  json_annotation:
  animate_do:
  cached_network_image:
  derry:
  carousel_slider:
  zoom_tap_animation:
  sms_autofill:
  snippet_coder_utils:
  expansion_tile_card:
  flutter_html:
  pin_code_fields:
  timer_count_down:
  shared_preferences:
  shimmer:
  http:
  hive:
  path_provider:
  hive_flutter:
  restart_app:
  flutter_rating_bar:
  url_launcher:
  flutter_localizations:
    sdk: flutter
#  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:
  hive_generator:
  freezed:
  json_serializable:

flutter:
#  generate: true
  uses-material-design: true

  assets:
    - assets/screenshots/
    - assets/screenshots/dark/
    - assets/images/


  fonts:
    - family: Noto Kufi Arabic
      fonts:
        - asset: assets/fonts/NotoKufiArabic-Black.ttf
        - asset: assets/fonts/NotoKufiArabic-Bold.ttf
        - asset: assets/fonts/NotoKufiArabic-ExtraBold.ttf
        - asset: assets/fonts/NotoKufiArabic-ExtraLight.ttf
        - asset: assets/fonts/NotoKufiArabic-Light.ttf
        - asset: assets/fonts/NotoKufiArabic-Medium.ttf
        - asset: assets/fonts/NotoKufiArabic-Regular.ttf
        - asset: assets/fonts/NotoKufiArabic-SemiBold.ttf
        - asset: assets/fonts/NotoKufiArabic-Thin.ttf
